[package]
name = "opsin"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
image = "0.25.6"
little_exif = "0.6.5"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
walkdir = "2.5.0"
