[package]
name = "opsin"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
image = "0.25.6"
rayon = "1.10.0"
serde = "1.0.219"
serde_json = "1.0.140"
udev = "0.9.3"
walkdir = "2.5.0"
