[input]
# Directory containing your source images
image_dir = "D:/DCIM"              
# Directory containing your .mts video stream files
video_dir = "D:/PRIVATE/AVCHD/BDMV/STREAM"  
# Where processed images & remuxed videos will be written
output    = "processed_output"     

[lut]
# The default .cube file you want to load at startup
selected = "SONY_CYBERSHOT_DSC-WX5.CUBE"
